## Задание № 2

### Урок 2.  Масштабирование признаков. L1- и L2-регуляризация. Стохастический градиентный спуск

#### Задача № 1

Сгенерировать датасет при помощи sklearn.datasets.make_regression и
обучить линейную модель при помощи градиентного и стохастического градиентного спуска.
Нанести среднеквадратичную ошибку для обоих методов на один график,
сделать выводы о разнице скорости сходимости каждого из методов.


In [11]:
import numpy as np
import matplotlib.pyplot as plt



In [46]:
from sklearn import datasets

n_samples = 100
X, y, coef = datasets.make_regression(n_samples=n_samples, n_features=5, coef=True, bias=5, noise=5,
                                      random_state=42)
X, y, coef

(array([[ 0.97511973, -0.67716171, -0.01224677, -0.89725437,  0.07580456],
        [ 0.08187414, -0.48536355,  0.75896922, -0.77282521, -0.23681861],
        [-1.4123037 , -0.90802408, -0.56228753, -1.01283112,  0.31424733],
        [-0.64511975,  0.36163603,  1.35624003, -0.07201012,  1.0035329 ],
        [-0.62269952,  0.28099187, -1.9520878 , -0.1517851 ,  0.58831721],
        [-0.45006547,  0.04698059, -1.59442766, -0.59937502,  0.0052437 ],
        [ 0.77463405,  0.44381943, -0.48423407,  1.26691115, -0.70766947],
        [ 0.35701549,  0.8496021 , -0.20812225, -0.49300093, -0.58936476],
        [-1.3044695 , -0.08912004,  0.38406545, -0.03269475, -2.0674421 ],
        [ 0.17318093, -1.24573878, -0.44651495,  0.85639879,  0.21409374],
        [ 0.29698467,  0.52194157,  0.78182287, -1.23695071, -1.32045661],
        [-1.72491783, -1.91328024, -0.46341769, -0.46572975,  0.24196227],
        [-1.98756891,  0.09176078,  0.8219025 ,  0.08704707, -0.29900735],
        [-0.0555477 , -1.

In [47]:
X.shape

(100, 5)

In [48]:
X = np.hstack((np.ones((X.shape[0],1)), X))
X.shape


array([[ 1.        ,  0.97511973, -0.67716171, -0.01224677, -0.89725437,
         0.07580456],
       [ 1.        ,  0.08187414, -0.48536355,  0.75896922, -0.77282521,
        -0.23681861],
       [ 1.        , -1.4123037 , -0.90802408, -0.56228753, -1.01283112,
         0.31424733],
       [ 1.        , -0.64511975,  0.36163603,  1.35624003, -0.07201012,
         1.0035329 ],
       [ 1.        , -0.62269952,  0.28099187, -1.9520878 , -0.1517851 ,
         0.58831721],
       [ 1.        , -0.45006547,  0.04698059, -1.59442766, -0.59937502,
         0.0052437 ],
       [ 1.        ,  0.77463405,  0.44381943, -0.48423407,  1.26691115,
        -0.70766947],
       [ 1.        ,  0.35701549,  0.8496021 , -0.20812225, -0.49300093,
        -0.58936476],
       [ 1.        , -1.3044695 , -0.08912004,  0.38406545, -0.03269475,
        -2.0674421 ],
       [ 1.        ,  0.17318093, -1.24573878, -0.44651495,  0.85639879,
         0.21409374],
       [ 1.        ,  0.29698467,  0.52194157,  0.

In [65]:
W = np.random.randn(X.shape[1])
W, W.shape, X.T.shape

(array([ 1.40668738, -1.43337184, -0.02597758, -1.22126365, -0.21223197,
         1.40917045]),
 (6,),
 (6, 100))

In [66]:
W @ X.T

array([ 0.33877339,  0.20533879,  4.79911652,  2.09509455,  5.53721459,
        4.13239046, -0.38990908,  0.40116814, -0.09669226,  1.85606785,
       -1.58560066,  4.93460242,  2.80964282, -0.85037409,  1.64069488,
        1.95387023,  0.66378885, -0.1558497 ,  0.96935369,  0.73283181,
       -0.94947132,  2.70308794,  4.80850888,  4.59655762,  1.39654781,
       -2.36905246,  0.50476686,  0.85895385,  2.70526592,  0.2047409 ,
        0.66157827,  0.97720752,  2.47981784, -2.29738166,  2.02717364,
        0.12038871, -1.70856843,  4.85411395,  0.36899631,  4.48776899,
        3.09451202,  1.56651258,  0.57786132,  1.67342276,  0.34231773,
       -1.19909915, -2.78370428,  1.80563847,  2.15204749, -0.70579788,
       -1.13714387,  6.39140036,  3.60516506, -1.62751591,  0.66826555,
        2.67026343,  3.40021081,  4.30284574,  0.5807944 , -1.89504584,
        2.99694558,  2.84246544,  0.71012071, -0.22812076,  0.33722099,
        0.39282822, -1.45014233,  2.99358305,  0.63842976,  2.03

In [50]:
def calc_mse(y, y_pred):
    err = np.mean((y - y_pred)**2)
    return err

In [61]:
def eval_model(X, y, iterations, alpha=1e-4):
    W = np.random.randn(X.shape[1])
    print( W)
    n = X.shape[0]
    print(n)
    for i in range(1, iterations+1):
        y_pred = np.dot(W, X)
        err = calc_mse(y, y_pred)
        W -= (alpha * (1/n * 2 * np.dot((y_pred - y), X.T)))
        if i % (iterations / 10) == 0:
            print(i, W, err)
    return W


In [62]:
eval_model(X, y, iterations=5000, alpha=1e-2)

[ 0.1925779   0.4412234  -0.76402154 -0.04372572  0.20662639  1.06477211]
100


ValueError: shapes (6,) and (100,6) not aligned: 6 (dim 0) != 100 (dim 0)

#### Задача № 2

Модифицировать решение первого задания путем добавления 𝐿2 -регуляризации
(в функцию, считающую MSE, нужно добавить норму вектора весов) и сравнить результаты.

#### Задача № 3 *

Модернизировать решение задания 2, заменив L2 регуляризацию на L1 регуляризацию.

